# Generated by Django 4.2.3 on 2023-08-25 13:09

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palettes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFavorite',
            new_name='Favorite',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='hex_color',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='palette',
            old_name='user',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='palette',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='palette',
            name='accent_colors',
            field=models.ManyToManyField(related_name='accent_palettes', to='palettes.color'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='dominant_colors',
            field=models.ManyToManyField(related_name='dominant_palettes', to='palettes.color'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
